--- # Variale playbook to install tree package
- hosts: demo
  user: ubuntu
  connection: ssh
  become: yes
  vars:
          pkgname: tree
  task:
                  - name: install tree package on Linux system
                    action: apt name='{{pkgname}}' state=present

                    # - name: install tree package on Linux system
                    #  action: apt name='{{pkgname}}' state=present

